"""add_is_developer

Revision ID: 8beee9809d87
Revises: 4d0ed3ddf86b
Create Date: 2026-06-10 11:21:50.520356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8beee9809d87'
down_revision: Union[str, None] = '4d0ed3ddf86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('is_developer', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'is_developer')
    # ### end Alembic commands ###
